// Lists the item art that exists on disk so items without bespoke art keep their procedural icon.
import { readdirSync, writeFileSync } from 'node:fs';
const ids = readdirSync('public/assets/gen/items').filter((f) => f.endsWith('.png')).map((f) => f.slice(0, -4)).sort();
writeFileSync('src/data/artManifest.ts', `// Generated by tools/make_art_manifest.mjs. Do not edit.\nexport const ITEM_ART = new Set<string>(${JSON.stringify(ids)});\n`);
console.log(ids.length, 'item art files');
